server:
  port: 8082  # Port pour le service voiture

spring:
  application:
    name: SERVICE-CAR  # Nom du service tel qu'il apparaîtra dans Eureka
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/carservicedb
    username: postgres
    password: salma
  jpa:
    hibernate:
      ddl-auto: update  # Crée ou met à jour automatiquement le schéma de la base
      show-sql: true    # Affiche les requêtes SQL générées

# Configuration Eureka (à ajouter)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL du serveur Eureka
  instance:
    prefer-ip-address: true  # Utilise l'adresse IP plutôt que le nom d'hôte